<?php
$saida .= '<div class="form-group row">';
$saida .= '<label class="col-sm-'.$tamLabel.' col-form-label">'.$required_label . ___($label).'</label>';
$saida .= '<div class="col-sm-'.$tamDiv.'">';
$saida .= '<div class="input-group m-b">';
$saida .= '<table width="100%" cellpadding="0" cellspacing="0" border="0">';
$saida .= '<tr>';
$saida .= '<td style="width:1%" valign="top">';
$saida .= $mostraIconeA;
$saida .= '</td>';
$saida .= '<td style="width:98%" valign="top">';
$saida .= $retorno;
$saida .= '</td>';
$saida .= '<td style="width:1%" valign="top">';
$saida .= $mostraIconeD;
$saida .= '</td>';
$saida .= '</tr>';
$saida .= '</table>';
$saida .= '</div>';
$saida .= $msg_complementar;
$saida .= '</div>';
$saida .= '</div>';	