<?php
use App\Repositories\Componentes;

$botaoHabilitaDesabilita = '';

$contador = ( !empty($data['contador']) ? $data['contador'] : 1 );
$titulo1 = ( !empty($data['titulo1']) ? $data['titulo1'] : 'Opa!' );
$titulo2 = ( !empty($data['titulo2']) ? $data['titulo2'] : 'Confirma a exclusão deste item?' );
$icone = ( !empty($data['icone']) ? $data['icone'] : 'question' );
$botao_confirmacao = ( !empty($data['botao_confirmacao']) ? $data['botao_confirmacao'] : ___('Sim') );
$cor_botao_confirmacao = ( !empty($data['cor_botao_confirmacao']) ? $data['cor_botao_confirmacao'] : '#3085d6' );
$botao_cancelamento = ( !empty($data['botao_cancelamento']) ? $data['botao_cancelamento'] : ___('Não') );
$cor_botao_cancelamento = ( !empty($data['cor_botao_cancelamento']) ? $data['cor_botao_cancelamento'] : '#d33' );
$form_method = ( !empty($data['form_method']) ? $data['form_method'] : 'POST' );
$titulo_toast = ( !empty($data['titulo_toast']) ? $data['titulo_toast'] : 'Item apagado com sucesso!' );
$sub_titulo_toast = ( !empty($data['sub_titulo_toast']) ? $data['sub_titulo_toast'] : 'Tudo certo!' );
$titulo_toast_pos = ( !empty($data['titulo_toast_pos']) ? $data['titulo_toast_pos'] : 'Desativando registro!' );
$sub_titulo_toast_pos = ( !empty($data['sub_titulo_toast_pos']) ? $data['sub_titulo_toast_pos'] : 'Aguarde!' );

$timeOut = ( !empty($data['timeOut']) ? $data['timeOut'] : 2000 );
$showEasing = ( !empty($data['showEasing']) ? $data['showEasing'] : 'linear' );
$showMethod = ( !empty($data['showMethod']) ? $data['showMethod'] : 'slideDown' );
$closeMethod = ( !empty($data['closeMethod']) ? $data['closeMethod'] : 'fadeOut' );
$closeDuration = ( !empty($data['closeDuration']) ? $data['closeDuration'] : 300 );
$closeEasing = ( !empty($data['closeEasing']) ? $data['closeEasing'] : 'swing' );
$complemento = '$this';

$botaoHabilitaDesabilita = "<script>";
$botaoHabilitaDesabilita .= "	$('body').on('click', '.botaoToaster', function () {";
$botaoHabilitaDesabilita .= "		botaoHabilitaDesabilita".$contador."($(this));";
$botaoHabilitaDesabilita .= "	});";
$botaoHabilitaDesabilita .= "	function botaoHabilitaDesabilita".$contador."(".$complemento.") {";
$botaoHabilitaDesabilita .= "		swal({";
$botaoHabilitaDesabilita .= "			title: '".$titulo1."',";
$botaoHabilitaDesabilita .= "			text: '".$titulo1."',";
$botaoHabilitaDesabilita .= "			type: 'question',";
$botaoHabilitaDesabilita .= "			confirmButtonText: '".$botao_confirmacao."',";
$botaoHabilitaDesabilita .= "			showCancelButton: true,";
$botaoHabilitaDesabilita .= "			cancelButtonText: '".$botao_cancelamento."',";
$botaoHabilitaDesabilita .= "			confirmButtonColor: '".$cor_botao_confirmacao."',";
$botaoHabilitaDesabilita .= "			cancelButtonColor: '".$cor_botao_cancelamento."',";
$botaoHabilitaDesabilita .= "		}).then((result) => {";
$botaoHabilitaDesabilita .= "			if( result.value ){";
$botaoHabilitaDesabilita .= "				botaoHabilitaDesabilitaAcao(".$complemento.");";
$botaoHabilitaDesabilita .= "			}";
$botaoHabilitaDesabilita .= "		});";
$botaoHabilitaDesabilita .= "	}";
$botaoHabilitaDesabilita .= "	function botaoHabilitaDesabilitaAcao(".$complemento."){";
$botaoHabilitaDesabilita .= "		$.ajax({";
$botaoHabilitaDesabilita .= "			url: ".$complemento.".data('url'),";
$botaoHabilitaDesabilita .= "			headers: {";
$botaoHabilitaDesabilita .= "				'X-CSRF-Token': $('meta[name=_token]').attr('content')";
$botaoHabilitaDesabilita .= "			},";
$botaoHabilitaDesabilita .= "			async: true,";
$botaoHabilitaDesabilita .= "			method: 'DELETE',";
$botaoHabilitaDesabilita .= "			data: ".$complemento.".serialize(),";
$botaoHabilitaDesabilita .= "			success: function (data) {";
$botaoHabilitaDesabilita .= "				toastr.clear();";
$botaoHabilitaDesabilita .= "				if( typeof tabela !== 'undefined' ) {";
$botaoHabilitaDesabilita .= "					tabela.ajax.reload();";
$botaoHabilitaDesabilita .= "				}";
$botaoHabilitaDesabilita .= "				if( typeof tabelaA !== 'undefined' ) {";
$botaoHabilitaDesabilita .= "					tabelaA.ajax.reload();";
$botaoHabilitaDesabilita .= "				}";
$botaoHabilitaDesabilita .= "				toastr.success(";
$botaoHabilitaDesabilita .= "					'".$titulo_toast."',";
$botaoHabilitaDesabilita .= "					'".$sub_titulo_toast."', {";
$botaoHabilitaDesabilita .= "						timeOut: ".$timeOut.",";
$botaoHabilitaDesabilita .= "						showEasing: '".$showEasing."',";
$botaoHabilitaDesabilita .= "						showMethod: '".$showMethod."',";
$botaoHabilitaDesabilita .= "						closeMethod: '".$closeMethod."',";
$botaoHabilitaDesabilita .= "						closeDuration: ".$closeDuration.",";
$botaoHabilitaDesabilita .= "						closeEasing: '".$closeEasing."',";
$botaoHabilitaDesabilita .= "						closeButton: false,";
$botaoHabilitaDesabilita .= "						progressBar: true,";
$botaoHabilitaDesabilita .= "					}";
$botaoHabilitaDesabilita .= "					);";
$botaoHabilitaDesabilita .= "				if( data.status != null ){";
$botaoHabilitaDesabilita .= "					window.location.reload();";
$botaoHabilitaDesabilita .= "				}";
$botaoHabilitaDesabilita .= "				if( data.redireciona != null ){";
$botaoHabilitaDesabilita .= "					window.location.href=data.redireciona;";
$botaoHabilitaDesabilita .= "				}";
$botaoHabilitaDesabilita .= "			},";
$botaoHabilitaDesabilita .= "			beforeSend: function () {";
$botaoHabilitaDesabilita .= "				toastr.info(";
$botaoHabilitaDesabilita .= "					'Desativando registro!',";
$botaoHabilitaDesabilita .= "					'Aguarde!', {";
$botaoHabilitaDesabilita .= "						showEasing: '".$showEasing."',";
$botaoHabilitaDesabilita .= "						showMethod: '".$showMethod."',";
$botaoHabilitaDesabilita .= "						closeMethod: '".$closeMethod."',";
$botaoHabilitaDesabilita .= "						closeDuration: ".$closeDuration.",";
$botaoHabilitaDesabilita .= "						closeEasing: '".$closeEasing."',";
$botaoHabilitaDesabilita .= "						closeButton: false,";
$botaoHabilitaDesabilita .= "						progressBar: true,";
$botaoHabilitaDesabilita .= "					}";
$botaoHabilitaDesabilita .= "					);";
$botaoHabilitaDesabilita .= "			},";
$botaoHabilitaDesabilita .= "			complete: function () {}";
$botaoHabilitaDesabilita .= "		});";
$botaoHabilitaDesabilita .= "	}";
$botaoHabilitaDesabilita .= "</script>";";