<?php
$botao = '<a href="#" class="btn btn-flex btn-primary h-40px fs-7 fw-bold" data-bs-toggle="modal" data-bs-target="#kt_modal_create_campaign">';
$botao .= ___($label);
$botao .= '</a>';

$botao .= '<div class="modal fade" id="kt_modal_create_campaign" tabindex="-1" aria-hidden="true" style="z-index: 999 !important">';
$botao .= '<div class="modal-dialog modal-fullscreen p-9">';
$botao .= '<div class="modal-content modal-rounded">';
$botao .= '<div class="modal-header py-7 d-flex justify-content-between">';
$botao .= '<h2>Create Campaign - 3</h2>';
$botao .= '<div class="btn btn-sm btn-icon btn-active-color-primary" data-bs-dismiss="modal">';
$botao .= '<i class="ki-outline ki-cross fs-1"></i>';
$botao .= '</div>';
$botao .= '</div>';
$botao .= '<div class="modal-body scroll-y m-5">';
$botao .= '<div class="stepper stepper-links d-flex flex-column" id="kt_modal_create_campaign_stepper">';
$botao .= '<div class="stepper-nav justify-content-center py-2">';
$botao .= '<div class="stepper-item me-5 me-md-15 current" data-kt-stepper-element="nav">';
$botao .= '<h3 class="stepper-title">Campaign Details</h3>';
$botao .= '</div>';
$botao .= '</div>';
$botao .= '<form class="mx-auto w-100 mw-600px pt-15 pb-10" novalidate="novalidate" id="kt_modal_create_campaign_stepper_form">';
$botao .= '<div class="current" data-kt-stepper-element="content">';
$botao .= '<div class="w-100">';
$botao .= '<div class="pb-10 pb-lg-15">';
$botao .= '<h2 class="fw-bold d-flex align-items-center text-dark">Setup Campaign Details';
$botao .= '<span class="ms-1" data-bs-toggle="tooltip" title="Campaign name will be used as reference within your campaign reports">';
$botao .= '<i class="ki-outline ki-information-5 text-gray-500 fs-6"></i>';
$botao .= '</span></h2>';
$botao .= '<div class="text-muted fw-semibold fs-6">If you need more info, please check out';
$botao .= '<a href="#" class="link-primary fw-bold">Help Page</a>.</div>';
$botao .= '</div>';
$botao .= '</div>';
$botao .= '</div>';
$botao .= '</form>';
$botao .= '</div>';
$botao .= '</div>';
$botao .= '</div>';
$botao .= '</div>';
$botao .= '</div>';